### ISSUE TITLE
ipt_REJECT : Unknown symbol nf_send_unreach & nf_send_reset

### ISSUE THREAD

**Issue by kinorai** [fenio/k3s-synology#1]
Hello,

I got my linux-4.4.x.txz here : 

https://global.download.synology.com/download/ToolChain/Synology%20NAS%20GPL%20Source/7.0-41890/geminilake/linux-4.4.x.txz

I followed your tuto to build ipt_REJECT.ko and xt_comment.ko.

I managed to add the xt_comment.ko into my kernel without any errors.

But when I try with ipt_REJECT.ko, I get this error :
```
insmod: ERROR: could not insert module /lib/modules/ipt_REJECT.ko: Unknown symbol in module
```

when I look at `dmesg`, I see those lines

```
ipt_REJECT: Unknown symbol nf_send_reset (err 0)
ipt_REJECT: Unknown symbol nf_send_unreach (err 0)
```

Those functions are indeed used in ipt_REJECT.c, is there any way to make this work?

I am on DSM 7.1.1-42962 Update 1.
```
ubuntu:~$ uname -a
Linux nas_name 4.4.180+ #42962 SMP Tue Sep 20 22:35:56 CST 2022 x86_64 GNU/Linux synology_geminilake_920+
```

**Comment by kinorai** [comment]
Well I found the answer, i forgot to add kernel module : nf_reject_ipv4.ko

**Comment by fenio** [comment]
Ok so since you've found a solution I'm closing this report. Thanks!
